export interface ProductReview {
  id: string;
  productId: number;
  customerName: string;
  customerEmail: string;
  rating: number;
  title: string;
  comment: string;
  images: string[];
  video?: string;
  verified: boolean;
  helpful: number;
  date: string;
  adminResponse?: {
    response: string;
    adminName: string;
    date: string;
  };
}

export interface ProductItem {
  id: number;
  name: string;
  category: "gemstones" | "rudraksha" | "bracelets" | "mala" | "ring";
  subcategory: string;
  price: number;
  originalPrice?: number;
  discount: number;
  image: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  description: string;
  benefits?: string[];
  // optional extras used by some categories
  weight?: string;
  origin?: string;
  certification?: string;
  mukhi?: string;
  size?: string;
  beads?: string;
  material?: string;
}

// Central catalog used by Store and ProductDetail
export const products: ProductItem[] = [
  // NOTE: The contents of this array were previously defined in Store.tsx
  // Gemstones
  {
    id: 1,
    name: "Yellow Sapphire (Pukhraj) - 2.5 Carats",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 25000,
    originalPrice: 31250,
    discount: 20,
    image: "/assets/sapphire-yellow.png",
    rating: 4.8,
    reviews: 124,
    inStock: true,
    description: "Natural Yellow Sapphire for Jupiter planet. Enhances wisdom, prosperity and spiritual growth.",
    benefits: ["Wealth & Prosperity", "Wisdom & Knowledge", "Spiritual Growth", "Career Success"],
    weight: "2.5 Carats",
    origin: "Sri Lanka",
    certification: "IGI Certified"
  },
  {
    id: 2,
    name: "Blue Sapphire (Neelam) - 1.8 Carats",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 18000,
    originalPrice: 22500,
    discount: 20,
    image: "/assets/sapphire-blue.png",
    rating: 4.7,
    reviews: 98,
    inStock: true,
    description: "Natural Blue Sapphire for Saturn planet. Brings discipline, focus and removes obstacles.",
    benefits: ["Discipline & Focus", "Removes Obstacles", "Career Stability", "Spiritual Protection"],
    weight: "1.8 Carats",
    origin: "Kashmir",
    certification: "GIA Certified"
  },
  {
    id: 3,
    name: "Ruby (Manik) - 3.2 Carats",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 45000,
    originalPrice: 56250,
    discount: 20,
    image: "/assets/ruby.png",
    rating: 4.9,
    reviews: 156,
    inStock: true,
    description: "Natural Ruby for Sun planet. Enhances leadership, confidence and vitality.",
    benefits: ["Leadership Qualities", "Confidence & Vitality", "Authority & Power", "Health & Energy"],
    weight: "3.2 Carats",
    origin: "Burma",
    certification: "IGI Certified"
  },
  {
    id: 4,
    name: "Emerald (Panna) - 2.1 Carats",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 32000,
    originalPrice: 40000,
    discount: 20,
    image: "/assets/panna.png",
    rating: 4.6,
    reviews: 87,
    inStock: true,
    description: "Natural Emerald for Mercury planet. Improves communication, intelligence and business success.",
    benefits: ["Communication Skills", "Intelligence & Memory", "Business Success", "Mental Clarity"],
    weight: "2.1 Carats",
    origin: "Colombia",
    certification: "GIA Certified"
  },
  {
    id: 5,
    name: "Red Coral (Moonga) - 4.5 Carats",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 15000,
    originalPrice: 18750,
    discount: 20,
    image: "/assets/redCoral.png",
    rating: 4.5,
    reviews: 73,
    inStock: true,
    description: "Natural Red Coral for Mars planet. Enhances courage, energy and removes enemies.",
    benefits: ["Courage & Energy", "Removes Enemies", "Physical Strength", "Leadership"],
    weight: "4.5 Carats",
    origin: "Mediterranean",
    certification: "IGI Certified"
  },
  {
    id: 6,
    name: "Hessonite (Gomed) - 3.8 Carats",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 12000,
    originalPrice: 15000,
    discount: 20,
    image: "/assets/hessonite.png",
    rating: 4.4,
    reviews: 65,
    inStock: true,
    description: "Natural Hessonite for Rahu planet. Removes negative energies and brings success.",
    benefits: ["Removes Negativity", "Success & Growth", "Protection from Evil", "Spiritual Progress"],
    weight: "3.8 Carats",
    origin: "Sri Lanka",
    certification: "IGI Certified"
  },
  {
    id: 7,
    name: "Cat's Eye (Lehsuniya) - 2.7 Carats",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 22000,
    originalPrice: 27500,
    discount: 20,
    image: "/assets/catEye.png",
    rating: 4.7,
    reviews: 92,
    inStock: true,
    description: "Natural Cat's Eye for Ketu planet. Provides protection and spiritual enlightenment.",
    benefits: ["Spiritual Protection", "Enlightenment", "Removes Fear", "Intuition"],
    weight: "2.7 Carats",
    origin: "Sri Lanka",
    certification: "GIA Certified"
  },
  {
    id: 8,
    name: "Opal Stone - 3.1 Carats",
    category: "gemstones",
    subcategory: "other-gems",
    price: 8000,
    originalPrice: 10000,
    discount: 20,
    image: "/assets/opal.png",
    rating: 4.3,
    reviews: 54,
    inStock: true,
    description: "Natural Opal stone for creativity and emotional balance.",
    benefits: ["Creativity", "Emotional Balance", "Love & Relationships", "Artistic Abilities"],
    weight: "3.1 Carats",
    origin: "Australia",
    certification: "IGI Certified"
  },
  // Rudraksha
  {
    id: 9,
    name: "5 Mukhi Rudraksha (Nepali)",
    category: "rudraksha",
    subcategory: "nepali",
    price: 2500,
    originalPrice: 3125,
    discount: 20,
    image: "/assets/rudraksha.png",
    rating: 4.8,
    reviews: 234,
    inStock: true,
    description: "Natural 5 Mukhi Rudraksha for Jupiter planet. Brings wisdom, knowledge and prosperity.",
    benefits: ["Wisdom & Knowledge", "Prosperity", "Spiritual Growth", "Academic Success"],
    mukhi: "5 Mukhi",
    origin: "Nepal",
    size: "12-14mm"
  },
  {
    id: 10,
    name: "6 Mukhi Rudraksha (Nepali)",
    category: "rudraksha",
    subcategory: "nepali",
    price: 3200,
    originalPrice: 4000,
    discount: 20,
    image: "/rudraksha.png",
    rating: 4.7,
    reviews: 189,
    inStock: true,
    description: "Natural 6 Mukhi Rudraksha for Venus planet. Enhances love, beauty and relationships.",
    benefits: ["Love & Relationships", "Beauty & Charm", "Artistic Abilities", "Material Comforts"],
    mukhi: "6 Mukhi",
    origin: "Nepal",
    size: "12-14mm"
  },
  {
    id: 11,
    name: "7 Mukhi Rudraksha (Nepali)",
    category: "rudraksha",
    subcategory: "nepali",
    price: 4500,
    originalPrice: 5625,
    discount: 20,
    image: "/rudraksha.png",
    rating: 4.9,
    reviews: 156,
    inStock: true,
    description: "Natural 7 Mukhi Rudraksha for Saturn planet. Brings discipline, focus and removes obstacles.",
    benefits: ["Discipline & Focus", "Removes Obstacles", "Career Stability", "Longevity"],
    mukhi: "7 Mukhi",
    origin: "Nepal",
    size: "12-14mm"
  },
  {
    id: 12,
    name: "9 Mukhi Rudraksha (Nepali)",
    category: "rudraksha",
    subcategory: "nepali",
    price: 8500,
    originalPrice: 10625,
    discount: 20,
    image: "/rudraksha.png",
    rating: 4.8,
    reviews: 98,
    inStock: true,
    description: "Natural 9 Mukhi Rudraksha for Ketu planet. Provides spiritual protection and enlightenment.",
    benefits: ["Spiritual Protection", "Enlightenment", "Removes Fear", "Intuition"],
    mukhi: "9 Mukhi",
    origin: "Nepal",
    size: "12-14mm"
  },
  // Additional items (mala, bracelets, gemstones webp)
  // The rest were copied from Store.tsx additions
  { id: 13, name: "7 Chakra Agate Bracelet", category: "bracelets", subcategory: "chakra", price: 799, originalPrice: 999, discount: 20, image: "/assets/serviceLogo.png", rating: 4.6, reviews: 145, inStock: true, description: "Beautiful 7 Chakra Agate Bracelet for energy balance and spiritual healing.", benefits: ["Energy Balance", "Spiritual Healing", "Chakra Alignment", "Emotional Stability"], material: "Agate", size: "Adjustable" },
  { id: 14, name: "Rudraksha Mala (108 Beads)", category: "mala", subcategory: "rudraksha", price: 3500, originalPrice: 4375, discount: 20, image: "/assets/rudraksha.png", rating: 4.8, reviews: 167, inStock: true, description: "Traditional 108 bead Rudraksha Mala for meditation and spiritual practices.", benefits: ["Meditation Aid", "Spiritual Growth", "Stress Relief", "Inner Peace"], beads: "108 Beads", material: "Rudraksha" },
  { id: 15, name: "5 Mukhi Rudraksha (Premium)", category: "rudraksha", subcategory: "nepali", price: 2999, originalPrice: 3499, discount: 15, image: "/assets/5mukhi.webp", rating: 4.7, reviews: 210, inStock: true, description: "Premium 5 Mukhi Rudraksha blessed for wisdom and prosperity.", benefits: ["Wisdom", "Prosperity", "Spiritual Growth"], mukhi: "5 Mukhi", origin: "Nepal", size: "12-14mm" },
  { id: 16, name: "5 Mukhi Silver Capped Rudraksha Mala", category: "mala", subcategory: "rudraksha", price: 5499, originalPrice: 6999, discount: 21, image: "/assets/5mukhisilverrudrakhshamala.webp", rating: 4.8, reviews: 134, inStock: true, description: "Silver-capped 5 Mukhi Rudraksha mala for meditation and protection.", benefits: ["Meditation", "Protection", "Calm Mind"], beads: "108 Beads", material: "Rudraksha" },
  { id: 17, name: "Crystal + Rudraksha Mala", category: "mala", subcategory: "rudraksha", price: 4499, originalPrice: 5499, discount: 18, image: "/assets/rudrakhsacrystal.webp", rating: 4.7, reviews: 98, inStock: true, description: "Combination mala for clarity and spiritual upliftment.", benefits: ["Clarity", "Healing", "Spiritual Upliftment"], beads: "108 Beads", material: "Crystal + Rudraksha" },
  { id: 18, name: "7 Chakra Healing Bracelet", category: "bracelets", subcategory: "chakra", price: 799, originalPrice: 999, discount: 20, image: "/assets/7chakra.webp", rating: 4.6, reviews: 175, inStock: true, description: "Align your chakras with natural stones.", benefits: ["Energy Balance", "Harmony", "Focus"], material: "Mixed Stones", size: "Adjustable" },
  { id: 19, name: "7 Chakra Lava Bracelet", category: "bracelets", subcategory: "chakra", price: 749, originalPrice: 949, discount: 21, image: "/assets/7chakralava.webp", rating: 4.5, reviews: 120, inStock: true, description: "Chakra stones with lava beads for essential oils.", benefits: ["Grounding", "Balance", "Aromatherapy"], material: "Lava + Stones", size: "Adjustable" },
  { id: 20, name: "7 Chakra Agate Bracelet", category: "bracelets", subcategory: "chakra", price: 699, originalPrice: 899, discount: 22, image: "/assets/7charaagate.webp", rating: 4.4, reviews: 98, inStock: true, description: "Agate based 7 chakra bracelet for stability.", benefits: ["Stability", "Balance", "Calm"], material: "Agate", size: "Adjustable" },
  { id: 21, name: "Black Obsidian Bracelet", category: "bracelets", subcategory: "crystal", price: 899, originalPrice: 1099, discount: 18, image: "/assets/blackobsidian.webp", rating: 4.6, reviews: 112, inStock: true, description: "Protection and grounding crystal bracelet.", benefits: ["Protection", "Grounding", "Shielding"], material: "Obsidian", size: "Adjustable" },
  { id: 22, name: "African Turquoise Bracelet", category: "bracelets", subcategory: "crystal", price: 999, originalPrice: 1199, discount: 17, image: "/assets/africanturquoise.webp", rating: 4.5, reviews: 84, inStock: true, description: "Growth and positive change.", benefits: ["Growth", "Positivity", "Calm"], material: "African Turquoise", size: "Adjustable" },
  { id: 23, name: "Opalite Bracelet", category: "bracelets", subcategory: "crystal", price: 799, originalPrice: 999, discount: 20, image: "/assets/opalite.webp", rating: 4.4, reviews: 77, inStock: true, description: "Soothing and emotional balance.", benefits: ["Soothing", "Balance", "Clarity"], material: "Opalite", size: "Adjustable" },
  { id: 24, name: "Natural Carnelian Bracelet", category: "bracelets", subcategory: "crystal", price: 859, originalPrice: 1049, discount: 18, image: "/assets/naturalcarnelian.webp", rating: 4.5, reviews: 69, inStock: true, description: "Confidence and motivation boost.", benefits: ["Confidence", "Motivation", "Creativity"], material: "Carnelian", size: "Adjustable" },
  { id: 25, name: "Aquamarine 10.7 Carat", category: "gemstones", subcategory: "other-gems", price: 52000, originalPrice: 59000, discount: 12, image: "/assets/aquamarine10.7.webp", rating: 4.7, reviews: 45, inStock: true, description: "High clarity aquamarine gemstone.", benefits: ["Calm", "Communication", "Clarity"], weight: "10.7 Carat", origin: "Brazil" },
  { id: 26, name: "Aquamarine 5.64 Carat", category: "gemstones", subcategory: "other-gems", price: 28500, originalPrice: 33500, discount: 15, image: "/assets/aquamarine5.64carat.webp", rating: 4.6, reviews: 33, inStock: true, description: "Beautiful aquamarine for serenity.", benefits: ["Serenity", "Balance"], weight: "5.64 Carat", origin: "Brazil" },
  { id: 27, name: "Bicolor Sapphire", category: "gemstones", subcategory: "other-gems", price: 74000, originalPrice: 82000, discount: 10, image: "/assets/bicolorsapphire.webp", rating: 4.8, reviews: 22, inStock: true, description: "Rare bicolor sapphire.", benefits: ["Wealth", "Focus"], weight: "Varies", origin: "Sri Lanka" },
  { id: 28, name: "Bicolor Tourmaline", category: "gemstones", subcategory: "other-gems", price: 38500, originalPrice: 46500, discount: 17, image: "/assets/bicolortoumiline.webp", rating: 4.6, reviews: 31, inStock: true, description: "Attractive bicolor tourmaline.", benefits: ["Balance", "Protection"], weight: "Varies", origin: "Africa" },
  { id: 29, name: "Emerald Premium", category: "gemstones", subcategory: "vedic-gems", price: 68000, originalPrice: 76000, discount: 11, image: "/assets/emerald.webp", rating: 4.7, reviews: 40, inStock: true, description: "Premium quality emerald.", benefits: ["Intelligence", "Business Success"], weight: "Varies", origin: "Colombia" },
  { id: 30, name: "Emerald 8.32 Carat", category: "gemstones", subcategory: "vedic-gems", price: 92000, originalPrice: 104000, discount: 12, image: "/assets/emerald8.32carat.webp", rating: 4.8, reviews: 27, inStock: true, description: "High carat emerald stone.", benefits: ["Communication", "Memory"], weight: "8.32 Carat", origin: "Zambia" },
  { id: 31, name: "Green Tourmaline", category: "gemstones", subcategory: "other-gems", price: 28500, originalPrice: 33500, discount: 15, image: "/assets/greentourmaline.webp", rating: 4.5, reviews: 29, inStock: true, description: "Healing green tourmaline.", benefits: ["Healing", "Heart Chakra"], weight: "Varies", origin: "Africa" },
  { id: 32, name: "Greenish Blue Tourmaline", category: "gemstones", subcategory: "other-gems", price: 31200, originalPrice: 36800, discount: 15, image: "/assets/greenishBluetourmaline.webp", rating: 4.5, reviews: 24, inStock: true, description: "Unique greenish blue tone tourmaline.", benefits: ["Balance", "Calm"], weight: "Varies", origin: "Africa" },
  { id: 33, name: "Chrome Tourmaline 4.03 Carat", category: "gemstones", subcategory: "other-gems", price: 41500, originalPrice: 48500, discount: 14, image: "/assets/chrometourmaline4.03carat.webp", rating: 4.6, reviews: 21, inStock: true, description: "Vivid chrome tourmaline.", benefits: ["Confidence", "Vitality"], weight: "4.03 Carat", origin: "Tanzania" },
  { id: 34, name: "Brown Tourmaline 7.18 Carat", category: "gemstones", subcategory: "other-gems", price: 26800, originalPrice: 31800, discount: 16, image: "/assets/browntourmiline7.18carate.webp", rating: 4.4, reviews: 18, inStock: true, description: "Earthy brown tourmaline.", benefits: ["Grounding", "Stability"], weight: "7.18 Carat", origin: "Africa" },
  { id: 35, name: "Burmese Ruby", category: "gemstones", subcategory: "vedic-gems", price: 125000, originalPrice: 142000, discount: 12, image: "/assets/burmeseruby.webp", rating: 4.9, reviews: 19, inStock: true, description: "Premium Burmese ruby.", benefits: ["Authority", "Vitality"], weight: "Varies", origin: "Myanmar" },
  { id: 36, name: "Star Ruby 7.56 Carat", category: "gemstones", subcategory: "vedic-gems", price: 84000, originalPrice: 94000, discount: 11, image: "/assets/startruby7.56carat.webp", rating: 4.7, reviews: 14, inStock: true, description: "Beautiful star ruby.", benefits: ["Protection", "Courage"], weight: "7.56 Carat", origin: "Sri Lanka" },
  { id: 37, name: "Star Ruby 9.48 Carat", category: "gemstones", subcategory: "vedic-gems", price: 112000, originalPrice: 126000, discount: 11, image: "/assets/starruby9.48carat.webp", rating: 4.8, reviews: 11, inStock: true, description: "High carat star ruby.", benefits: ["Protection", "Strength"], weight: "9.48 Carat", origin: "Sri Lanka" },
  { id: 38, name: "Rubellite 3.47 Carat", category: "gemstones", subcategory: "other-gems", price: 38800, originalPrice: 44800, discount: 13, image: "/assets/rubelite3.47carat.webp", rating: 4.6, reviews: 17, inStock: true, description: "Bright rubellite gemstone.", benefits: ["Love", "Vitality"], weight: "3.47 Carat", origin: "Madagascar" },
  { id: 39, name: "Rubellite", category: "gemstones", subcategory: "other-gems", price: 32000, originalPrice: 38000, discount: 16, image: "/assets/rubelite.webp", rating: 4.5, reviews: 20, inStock: true, description: "Attractive rubellite stone.", benefits: ["Love", "Courage"], weight: "Varies", origin: "Africa" },
  { id: 40, name: "Shree Pyrite Yantra", category: "gemstones", subcategory: "other-gems", price: 2100, originalPrice: 2600, discount: 19, image: "/assets/shreepyriteyantra.webp", rating: 4.4, reviews: 28, inStock: true, description: "Pyrite yantra for prosperity.", benefits: ["Prosperity", "Protection"], weight: "—", origin: "India" },
  // New Products with Latest Assets
  {
    id: 41,
    name: "Blue Sapphire (Neelam) - Premium Quality",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 35000,
    originalPrice: 42000,
    discount: 17,
    image: "/assets/blueSapphire.jpg",
    rating: 4.9,
    reviews: 89,
    inStock: true,
    description: "Premium quality Blue Sapphire with excellent clarity and color. Perfect for Saturn planet.",
    benefits: ["Discipline & Focus", "Career Success", "Spiritual Protection", "Wealth"],
    weight: "3.5 Carats",
    origin: "Kashmir",
    certification: "GIA Certified"
  },
  {
    id: 42,
    name: "Blue Sapphire Ring - Luxury Collection",
    category: "gemstones",
    subcategory: "jewelry",
    price: 55000,
    originalPrice: 65000,
    discount: 15,
    image: "/assets/blueSapphire2.jpg",
    rating: 4.8,
    reviews: 67,
    inStock: true,
    description: "Luxury Blue Sapphire ring with diamond accents. Perfect for special occasions.",
    benefits: ["Elegance", "Status", "Protection", "Wealth"],
    weight: "4.2 Carats",
    origin: "Sri Lanka",
    certification: "IGI Certified"
  },
  {
    id: 43,
    name: "Cat's Eye (Lehsunia) - Natural",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 28000,
    originalPrice: 35000,
    discount: 20,
    image: "/assets/catseye.jpg",
    rating: 4.7,
    reviews: 112,
    inStock: true,
    description: "Natural Cat's Eye gemstone for Ketu planet. Brings spiritual awakening and protection.",
    benefits: ["Spiritual Awakening", "Protection from Evil", "Intuition", "Moksha"],
    weight: "2.8 Carats",
    origin: "Sri Lanka",
    certification: "GIA Certified"
  },
  {
    id: 44,
    name: "Cat's Eye Ring - Designer",
    category: "gemstones",
    subcategory: "jewelry",
    price: 45000,
    originalPrice: 55000,
    discount: 18,
    image: "/assets/catseyeRing.jpg",
    rating: 4.6,
    reviews: 45,
    inStock: true,
    description: "Designer Cat's Eye ring with intricate gold work. Perfect for spiritual seekers.",
    benefits: ["Spiritual Growth", "Protection", "Elegance", "Status"],
    weight: "3.1 Carats",
    origin: "India",
    certification: "Hallmark Certified"
  },
  {
    id: 45,
    name: "Diamond - Premium Quality",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 85000,
    originalPrice: 105000,
    discount: 19,
    image: "/assets/diamond1.jpg",
    rating: 4.9,
    reviews: 156,
    inStock: true,
    description: "Premium quality Diamond for Venus planet. Enhances luxury, beauty and relationships.",
    benefits: ["Luxury & Beauty", "Love & Relationships", "Wealth", "Status"],
    weight: "2.5 Carats",
    origin: "South Africa",
    certification: "GIA Certified"
  },
  {
    id: 46,
    name: "Diamond Ring - Wedding Collection",
    category: "gemstones",
    subcategory: "jewelry",
    price: 125000,
    originalPrice: 150000,
    discount: 17,
    image: "/assets/diamondRing.jpg",
    rating: 4.8,
    reviews: 89,
    inStock: true,
    description: "Exquisite diamond ring perfect for weddings and special occasions.",
    benefits: ["Love & Commitment", "Elegance", "Status", "Wealth"],
    weight: "3.8 Carats",
    origin: "Belgium",
    certification: "GIA Certified"
  },
  {
    id: 47,
    name: "Pearl (Moti) - Natural",
    category: "gemstones",
    subcategory: "rashi-ratna",
    price: 15000,
    originalPrice: 18000,
    discount: 17,
    image: "/assets/motiRing.jpg",
    rating: 4.5,
    reviews: 134,
    inStock: true,
    description: "Natural Pearl for Moon planet. Brings emotional balance and mental peace.",
    benefits: ["Emotional Balance", "Mental Peace", "Fertility", "Motherhood"],
    weight: "8-10mm",
    origin: "Japan",
    certification: "Natural Pearl"
  },
  {
    id: 48,
    name: "Pearl Ring - Classic Design",
    category: "gemstones",
    subcategory: "jewelry",
    price: 25000,
    originalPrice: 30000,
    discount: 17,
    image: "/assets/motiRing.jpg",
    rating: 4.4,
    reviews: 78,
    inStock: true,
    description: "Classic pearl ring design with elegant gold setting.",
    benefits: ["Elegance", "Emotional Balance", "Femininity", "Grace"],
    weight: "10-12mm",
    origin: "Japan",
    certification: "Natural Pearl"
  },
  {
    id: 49,
    name: "Opal - Fire Opal",
    category: "gemstones",
    subcategory: "other-gems",
    price: 12000,
    originalPrice: 15000,
    discount: 20,
    image: "/assets/opal.jpg",
    rating: 4.3,
    reviews: 67,
    inStock: true,
    description: "Beautiful Fire Opal with vibrant colors. Enhances creativity and imagination.",
    benefits: ["Creativity", "Imagination", "Artistic Skills", "Inspiration"],
    weight: "2.2 Carats",
    origin: "Australia",
    certification: "Natural Opal"
  },
  {
    id: 50,
    name: "Evil Eye Protection Bracelet",
    category: "bracelets",
    subcategory: "protection",
    price: 2500,
    originalPrice: 3200,
    discount: 22,
    image: "/assets/evileye.jpg",
    rating: 4.6,
    reviews: 234,
    inStock: true,
    description: "Evil Eye protection bracelet with natural stones. Protects from negative energy.",
    benefits: ["Protection", "Negative Energy Removal", "Good Luck", "Peace"],
    weight: "—",
    origin: "Turkey",
    certification: "Handmade"
  },
  {
    id: 51,
    name: "Pirate Style Bracelet",
    category: "bracelets",
    subcategory: "fashion",
    price: 1800,
    originalPrice: 2200,
    discount: 18,
    image: "/assets/piratebracelate.jpg",
    rating: 4.2,
    reviews: 89,
    inStock: true,
    description: "Unique pirate-style bracelet with authentic design elements.",
    benefits: ["Style", "Uniqueness", "Adventure", "Boldness"],
    weight: "—",
    origin: "India",
    certification: "Handcrafted"
  },
  {
    id: 52,
    name: "Designer Bracelet - Gold",
    category: "bracelets",
    subcategory: "luxury",
    price: 35000,
    originalPrice: 42000,
    discount: 17,
    image: "/assets/bracelate1.jpg",
    rating: 4.7,
    reviews: 56,
    inStock: true,
    description: "Luxury gold bracelet with intricate design and precious stones.",
    benefits: ["Luxury", "Status", "Elegance", "Wealth"],
    weight: "25g",
    origin: "India",
    certification: "Hallmark Gold"
  },
  {
    id: 53,
    name: "10 Mukhi Rudraksha - Premium",
    category: "rudraksha",
    subcategory: "premium",
    price: 8500,
    originalPrice: 10500,
    discount: 19,
    image: "/assets/10mukhirudrakhs.jpg",
    rating: 4.8,
    reviews: 145,
    inStock: true,
    description: "Premium 10 Mukhi Rudraksha for Lord Hanuman. Brings courage and strength.",
    benefits: ["Courage", "Strength", "Protection", "Success"],
    weight: "—",
    origin: "Nepal",
    certification: "Authentic"
  },
  {
    id: 54,
    name: "10 Mukhi Rudraksha - Special",
    category: "rudraksha",
    subcategory: "special",
    price: 12000,
    originalPrice: 15000,
    discount: 20,
    image: "/assets/10mukh2.jpg",
    rating: 4.9,
    reviews: 98,
    inStock: true,
    description: "Special 10 Mukhi Rudraksha with excellent quality and natural finish.",
    benefits: ["Courage", "Leadership", "Protection", "Victory"],
    weight: "—",
    origin: "Nepal",
    certification: "Authentic"
  },
  {
    id: 55,
    name: "5 Mukhi Rudraksha - Standard",
    category: "rudraksha",
    subcategory: "standard",
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    image: "/assets/5 mukhi.jpg",
    rating: 4.5,
    reviews: 267,
    inStock: true,
    description: "Standard 5 Mukhi Rudraksha for Lord Shiva. Brings peace and meditation.",
    benefits: ["Peace", "Meditation", "Spiritual Growth", "Calmness"],
    weight: "—",
    origin: "Nepal",
    certification: "Authentic"
  },
  {
    id: 56,
    name: "5 Mukhi Rudraksha - Ridkharkh",
    category: "rudraksha",
    subcategory: "special",
    price: 1800,
    originalPrice: 2200,
    discount: 18,
    image: "/assets/5 mukhi ridkharkh.jpg",
    rating: 4.6,
    reviews: 123,
    inStock: true,
    description: "Special 5 Mukhi Rudraksha with Ridkharkh variety. Enhanced spiritual benefits.",
    benefits: ["Spiritual Growth", "Peace", "Meditation", "Divine Connection"],
    weight: "—",
    origin: "Nepal",
    certification: "Authentic"
  },
  {
    id: 57,
    name: "Gouri Shankar Rudraksha - Premium",
    category: "rudraksha",
    subcategory: "premium",
    price: 25000,
    originalPrice: 30000,
    discount: 17,
    image: "/assets/GouriShankarRudraksh.jpg",
    rating: 4.9,
    reviews: 78,
    inStock: true,
    description: "Premium Gouri Shankar Rudraksha representing Lord Shiva and Parvati.",
    benefits: ["Marital Harmony", "Love", "Unity", "Divine Blessing"],
    weight: "—",
    origin: "Nepal",
    certification: "Authentic"
  },
  {
    id: 58,
    name: "Gouri Shankar Rudraksha Mala",
    category: "mala",
    subcategory: "premium",
    price: 45000,
    originalPrice: 55000,
    discount: 18,
    image: "/assets/GouriShankarRudrakshMala.jpg",
    rating: 4.8,
    reviews: 45,
    inStock: true,
    description: "Premium Gouri Shankar Rudraksha Mala with 108+1 beads for meditation.",
    benefits: ["Marital Harmony", "Meditation", "Spiritual Growth", "Divine Blessing"],
    weight: "—",
    origin: "Nepal",
    certification: "Authentic"
  },
  {
    id: 59,
    name: "Rudraksha Mini Crystal Tree",
    category: "rudraksha",
    subcategory: "decorative",
    price: 3500,
    originalPrice: 4200,
    discount: 17,
    image: "/assets/Rudraksha Mini Crystal Tree.jpg",
    rating: 4.4,
    reviews: 89,
    inStock: true,
    description: "Beautiful Rudraksha mini crystal tree for home decoration and positive energy.",
    benefits: ["Positive Energy", "Home Decoration", "Spiritual Ambiance", "Peace"],
    weight: "—",
    origin: "India",
    certification: "Handcrafted"
  },
  {
    id: 60,
    name: "Original 5 Mukhi Rudraksha Mala",
    category: "mala",
    subcategory: "standard",
    price: 2800,
    originalPrice: 3500,
    discount: 20,
    image: "/assets/Original 5 Mukhi Rudraksha Mala 108+1 Beads (Lab Certified) Wood Necklace.jpg",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    description: "Original 5 Mukhi Rudraksha Mala with 108+1 beads and lab certification.",
    benefits: ["Meditation", "Peace", "Spiritual Growth", "Authenticity"],
    weight: "—",
    origin: "Nepal",
    certification: "Lab Certified"
  },
  // Ring Products from Recent Assets
  {
    id: 61,
    name: "Gold Plated Rectangular Turquoise Ring",
    category: "ring",
    subcategory: "turquoise-rings",
    price: 8500,
    originalPrice: 10500,
    discount: 19,
    image: "/assets/goldplatedRectengularTarquishRing.jpg",
    rating: 4.6,
    reviews: 89,
    inStock: true,
    description: "Elegant gold plated rectangular turquoise ring with beautiful blue-green stone.",
    benefits: ["Communication", "Calmness", "Protection", "Wisdom"],
    weight: "2.1 Carats",
    origin: "Afghanistan",
    certification: "Natural Turquoise"
  },
  {
    id: 62,
    name: "Sterling Silver Islamic Ring",
    category: "ring",
    subcategory: "islamic-rings",
    price: 4500,
    originalPrice: 5500,
    discount: 18,
    image: "/assets/stermicSilverIslamicRing.jpg",
    rating: 4.5,
    reviews: 134,
    inStock: true,
    description: "Beautiful sterling silver Islamic ring with traditional design and spiritual significance.",
    benefits: ["Spiritual Protection", "Faith", "Peace", "Blessings"],
    weight: "8g",
    origin: "India",
    certification: "Hallmark Silver"
  },
  {
    id: 63,
    name: "Turquoise Matrix Pendant Ring",
    category: "ring",
    subcategory: "turquoise-rings",
    price: 6800,
    originalPrice: 8200,
    discount: 17,
    image: "/assets/tarquirish matrix pendentRing.jpg",
    rating: 4.4,
    reviews: 76,
    inStock: true,
    description: "Unique turquoise matrix ring with natural patterns and earthy tones.",
    benefits: ["Grounding", "Stability", "Natural Energy", "Protection"],
    weight: "1.8 Carats",
    origin: "Nevada, USA",
    certification: "Natural Turquoise"
  },
  {
    id: 64,
    name: "Turquoise Gold Ring",
    category: "ring",
    subcategory: "turquoise-rings",
    price: 12000,
    originalPrice: 14500,
    discount: 17,
    image: "/assets/tarquish gold.jpg",
    rating: 4.7,
    reviews: 98,
    inStock: true,
    description: "Premium turquoise gold ring with excellent craftsmanship and beautiful blue stone.",
    benefits: ["Luxury", "Communication", "Calmness", "Status"],
    weight: "2.5 Carats",
    origin: "Persia",
    certification: "Natural Turquoise"
  },
  {
    id: 65,
    name: "Turquoise Silver Gemstone Ring",
    category: "ring",
    subcategory: "turquoise-rings",
    price: 5500,
    originalPrice: 6800,
    discount: 19,
    image: "/assets/tarquishsilverGemsstone.jpg",
    rating: 4.3,
    reviews: 67,
    inStock: true,
    description: "Silver turquoise gemstone ring with natural blue-green color and healing properties.",
    benefits: ["Healing", "Communication", "Protection", "Balance"],
    weight: "1.9 Carats",
    origin: "Tibet",
    certification: "Natural Turquoise"
  },
  {
    id: 66,
    name: "The Patterned Brown and White Stone Ring",
    category: "ring",
    subcategory: "natural-stone-rings",
    price: 4200,
    originalPrice: 5200,
    discount: 19,
    image: "/assets/The Patterned Brown and White Stone Ring.jpg",
    rating: 4.2,
    reviews: 45,
    inStock: true,
    description: "Unique patterned brown and white stone ring with natural design and earthy appeal.",
    benefits: ["Grounding", "Stability", "Natural Beauty", "Protection"],
    weight: "1.5 Carats",
    origin: "India",
    certification: "Natural Stone"
  },
  {
    id: 67,
    name: "Blue Sapphire Islamic Ring",
    category: "ring",
    subcategory: "islamic-rings",
    price: 25000,
    originalPrice: 30000,
    discount: 17,
    image: "/assets/blueSapphireislamic.jpg",
    rating: 4.8,
    reviews: 112,
    inStock: true,
    description: "Premium blue sapphire Islamic ring with traditional design and spiritual significance.",
    benefits: ["Discipline", "Focus", "Spiritual Protection", "Wisdom"],
    weight: "2.8 Carats",
    origin: "Kashmir",
    certification: "GIA Certified"
  },
  {
    id: 68,
    name: "Dark Green Stone Ring",
    category: "ring",
    subcategory: "natural-stone-rings",
    price: 7500,
    originalPrice: 9200,
    discount: 18,
    image: "/assets/darkg=Greenstone.jpg",
    rating: 4.5,
    reviews: 78,
    inStock: true,
    description: "Beautiful dark green stone ring with natural color and healing properties.",
    benefits: ["Healing", "Growth", "Nature Connection", "Balance"],
    weight: "2.3 Carats",
    origin: "Brazil",
    certification: "Natural Green Stone"
  },
  {
    id: 69,
    name: "Red Pink Stone Ring",
    category: "ring",
    subcategory: "natural-stone-rings",
    price: 6200,
    originalPrice: 7600,
    discount: 18,
    image: "/assets/redPinkStone.jpg",
    rating: 4.4,
    reviews: 56,
    inStock: true,
    description: "Elegant red pink stone ring with vibrant color and feminine appeal.",
    benefits: ["Love", "Passion", "Feminine Energy", "Creativity"],
    weight: "1.7 Carats",
    origin: "Madagascar",
    certification: "Natural Stone"
  }
];

// Sample product reviews data
export const productReviews: ProductReview[] = [
  {
    id: "1",
    productId: 1,
    customerName: "Priya Sharma",
    customerEmail: "priya.sharma@email.com",
    rating: 5,
    title: "Excellent quality and fast delivery!",
    comment: "I've been wearing this ruby for 3 months now and I can feel the positive energy. The quality is outstanding and the delivery was super fast. Highly recommended!",
    images: ["/assets/review1.jpg", "/assets/review2.jpg"],
    video: "/assets/review-video1.mp4",
    verified: true,
    helpful: 12,
    date: "2024-01-15",
    adminResponse: {
      response: "Thank you for your wonderful feedback, Priya! We're delighted to hear about your positive experience with our ruby. Wishing you continued prosperity!",
      adminName: "Admin Team",
      date: "2024-01-16"
    }
  },
  {
    id: "2",
    productId: 1,
    customerName: "Rajesh Kumar",
    customerEmail: "rajesh.kumar@email.com",
    rating: 4,
    title: "Good product, minor packaging issue",
    comment: "The ruby is beautiful and authentic. However, the packaging could be better. The stone arrived safely but the box was slightly damaged during shipping.",
    images: ["/assets/review3.jpg"],
    verified: true,
    helpful: 8,
    date: "2024-01-10",
    adminResponse: {
      response: "Thank you for your feedback, Rajesh. We apologize for the packaging issue and have improved our shipping process. We're glad you're satisfied with the product quality!",
      adminName: "Admin Team",
      date: "2024-01-11"
    }
  },
  {
    id: "3",
    productId: 2,
    customerName: "Anita Patel",
    customerEmail: "anita.patel@email.com",
    rating: 5,
    title: "Perfect emerald, exactly as described",
    comment: "This emerald is absolutely stunning! The color is vibrant and the clarity is excellent. The certification is authentic and the customer service was exceptional.",
    images: ["/assets/review4.jpg", "/assets/review5.jpg", "/assets/review6.jpg"],
    verified: true,
    helpful: 15,
    date: "2024-01-08"
  },
  {
    id: "4",
    productId: 3,
    customerName: "Vikram Singh",
    customerEmail: "vikram.singh@email.com",
    rating: 5,
    title: "Amazing sapphire, great value for money",
    comment: "I was skeptical about buying online, but this sapphire exceeded my expectations. The blue color is mesmerizing and the craftsmanship is top-notch.",
    images: ["/assets/review7.jpg"],
    video: "/assets/review-video2.mp4",
    verified: true,
    helpful: 20,
    date: "2024-01-05"
  },
  {
    id: "5",
    productId: 4,
    customerName: "Sunita Reddy",
    customerEmail: "sunita.reddy@email.com",
    rating: 4,
    title: "Beautiful diamond, slight delay in delivery",
    comment: "The diamond is gorgeous and the quality is excellent. There was a slight delay in delivery due to certification process, but it was worth the wait.",
    images: ["/assets/review8.jpg", "/assets/review9.jpg"],
    verified: true,
    helpful: 6,
    date: "2024-01-03"
  },
  {
    id: "6",
    productId: 5,
    customerName: "Amit Jain",
    customerEmail: "amit.jain@email.com",
    rating: 5,
    title: "Outstanding yellow sapphire",
    comment: "This yellow sapphire is perfect for my Jupiter remedy. The color is brilliant and I can feel the positive energy. The astrological consultation was also very helpful.",
    images: ["/assets/review10.jpg"],
    verified: true,
    helpful: 18,
    date: "2024-01-01"
  },
  {
    id: "7",
    productId: 6,
    customerName: "Deepika Mehta",
    customerEmail: "deepika.mehta@email.com",
    rating: 5,
    title: "Lovely pearl necklace",
    comment: "The pearl necklace is elegant and the pearls are perfectly matched. The luster is beautiful and it looks great with both traditional and modern outfits.",
    images: ["/assets/review11.jpg", "/assets/review12.jpg"],
    verified: true,
    helpful: 14,
    date: "2023-12-28"
  },
  {
    id: "8",
    productId: 7,
    customerName: "Ravi Gupta",
    customerEmail: "ravi.gupta@email.com",
    rating: 4,
    title: "Good quality, could be better priced",
    comment: "The amethyst is good quality and the color is nice. However, I think it's slightly overpriced compared to other sellers. The service was good though.",
    images: ["/assets/review13.jpg"],
    verified: true,
    helpful: 7,
    date: "2023-12-25"
  }
];
